export const KEYS = {
	// Recoil
	PROPERTIES: "PROPERTIES",
	ACCOUNT_ADDRESS: "ACCOUNT_ADDRESS",

	// API
	ASYNC_AUTH_TOKEN: "ASYNC_AUTH_TOKEN",
	ASYNC_NFT_MINT: "ASYNC_NFT_MINT",
	ASYNC_MY_NFTS: "ASYNC_MY_NFTS",
	ASYNC_NFT_INFO: "ASYNC_NFT_INFO",
	ASYNC_METADATA: "ASYNC_METADATA",
};
