export const Keys = {
	AUTH_TOKEN_ASYNC: "AUTH_TOKEN_ASYNC",
	
	DEFAULT_ITEMS_ASYNC: "DEFAULT_ITEM_ASYNC",
	USER_ITEMS_ASYNC: "USER_ITEMS_ASYNC",
	CREATE_USER_ITEM_ASYNC: "CREATE_USER_ITEM_ASYNC",
	UPDATE_USER_ITEM_ASYNC: "UPDATE_USER_ITEM_ASYNC",
	HISTORY_DATA_ASYNC: "HISTORY_DATA_ASYNC",
	SELECTED_ITEM_ASYNC: "SELECTED_ITEM_ASYNC",
};
